POST {{base_url}}/user/register
Content-Type: application/json

{
  "first_name": "Jhon",
  "last_name": "Smith",
  "email": "mail@email.com",
  "password": "secret"
}

###

POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "mail@email.com",
  "password": "secret"
}
> {%
    client.global.set("access_token", response.body.tokens.access_token);
    client.global.set("refresh_token", response.body.tokens.refresh_token);
%}

###
POST {{base_url}}/auth/refreshToken
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh_token": "{{refresh_token}}"
}

### Auth Hello

GET {{base_url}}/auth/hello
Authorization: Bearer {{access_token}}

###
GET {{base_url}}/user
Authorization: Bearer {{access_token}}

###
DELETE {{base_url}}/user
Authorization: Bearer {{access_token}}

###

POST {{base_url}}/auth/sendOtp
Authorization: Bearer {{access_token}}

###
POST {{base_url}}/auth/verifyOtp
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "otp": "Q39MZK"
}
